# See the dedicated "version" documentation section.
version: "2"
linters:
  # See the dedicated "linters" documentation section.
  default: all
formatters:
  # See the dedicated "formatters" documentation section.
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    warn-unused: true
issues:
  # See the dedicated "issues" documentation section.
  new-from-merge-base: "develop"
run:
  # See the dedicated "run" documentation section.
  timeout: 30s
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info