version: 2

run:
  timeout: 2m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gofumpt

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  severity:
    default: error

# Optionnel : pour exclure des fichiers ou répertoires
# exclude-rules:
#   - path: _gen/
#     linters:
#       - gofmt
