version: "2"

run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

# Optionnel : pour exclure des fichiers ou répertoires
# exclude-rules:
#   - path: _gen/
#     linters:
#       - gofmt
