name: Go CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build & Test All Modules
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Find Go Modules
      id: mods
      run: |
        echo "modules<<EOF" >> $GITHUB_OUTPUT
        find . -name 'go.mod' -not -path './go.work' -exec dirname {} \; >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Run go test for each module
      run: |
        for module in ${{ steps.mods.outputs.modules }}; do
          echo "📦 Testing $module"
          cd $module
          go mod tidy
          go test -v -race -cover ./...
          cd -
        done

    - name: Run golangci-lint for each module
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-cache: true
        args: |
          run --timeout 2m
      env:
        GOLANGCI_LINT_RUN_MODULES: ${{ steps.mods.outputs.modules }}
